import type { VenueData } from '@/types';

/**
 * Builds a self-contained React TSX file that renders the given venue as an
 * interactive seat map with nested sections, pattern fills, arc sections and
 * runtime interactions. The output has zero dependencies beyond React, uses
 * inline SVG for every visual element and exposes props for state + callbacks.
 */
export function generateComponentSource(data: VenueData, componentName = 'SeatMap'): string {
  const venueJson = JSON.stringify(data, null, 2);

  return `/**
 * ${componentName} — generated by Eskat Seating Design Tool
 *
 * Self-contained interactive seat map. Zero dependencies beyond React.
 *
 * Features:
 *   - Nested sections (container → sub-sections → seats) with animated drill-in
 *   - Pattern fills (dots, grid, stripes, custom SVG)
 *   - Arc sections, polygons with bezier-curved edges
 *   - Runtime interactions: tooltip, select / drillIn / url / event
 *   - Marquee + shift multi-select, zoom/pan, arrow-key navigation
 *
 * Props:
 *   - initialSeatStates?: Record<string, 'available' | 'reserved' | 'disabled'>
 *   - onSeatSelect?:      (seatId, seatInfo) => void
 *   - onSelectionChange?: (selectedIds) => void
 *   - onDrillIn?:         (sectionId) => void
 *   - onDrillOut?:        () => void
 *   - initialDrillPath?:  string[]
 *   - readOnly?:          boolean
 *   - maxSelectable?:     number
 *   - className?:         string
 */

import React, {
  useCallback,
  useEffect,
  useMemo,
  useRef,
  useState,
} from 'react';

// ─── TUNABLE CONFIG ───────────────────────────────────────────────
// Integrators can freely edit these values to theme/behavior the map.

const SEAT_CONFIG = {
  colors: {
    available: '#a855f7',
    reserved: '#ef4444',
    disabled: '#4b5563',
    selected: '#f59e0b',
    background: '#0f172a',
    sectionLabel: 'rgba(255,255,255,0.95)',
    accessibility: '#0ea5e9',
    marqueeStroke: '#a855f7',
    marqueeFill: 'rgba(168, 85, 247, 0.2)',
    breadcrumbBg: 'rgba(15, 23, 42, 0.78)',
    breadcrumbActive: '#a855f7',
  },
  interaction: {
    minZoom: 0.4,
    maxZoom: 4,
    zoomStep: 0.1,
    wheelZoomSpeed: 0.0015,
    hoverOutline: true,
    marqueeSelect: true,
    shiftMultiSelect: true,
    drillAnimationMs: 320,
    showBreadcrumb: true,
    allowEscapeToDrillUp: true,
    defaultContainerClick: 'drillIn' as 'drillIn' | 'select' | 'url' | 'event',
  },
  layout: {
    seatIcon: 'chair',
    sectionBorderRadius: 6,
    seatBorderRadius: 4,
    showSectionLabels: true,
    showPriceBadges: true,
  },
} as const;

// ─── INLINE VENUE DATA ────────────────────────────────────────────
// Generated from the Eskat designer. Do not edit by hand — regenerate
// instead to preserve layout fidelity.

const VENUE_DATA = ${venueJson} as const;

// ─── TYPES ────────────────────────────────────────────────────────

export type SeatState = 'available' | 'reserved' | 'disabled';
type AnySection = any;

export interface SeatInfo {
  id: string;
  label: string;
  rowLabel: string;
  seatNumber: string;
  sectionId: string;
  sectionName: string;
  sectionPath: string[];
  price: number;
  currency: string;
  state: SeatState;
  accessible: boolean;
}

export interface ${componentName}Props {
  initialSeatStates?: Record<string, SeatState>;
  onSeatSelect?: (seatId: string, info: SeatInfo) => void;
  onSelectionChange?: (selectedIds: string[]) => void;
  onDrillIn?: (sectionId: string) => void;
  onDrillOut?: () => void;
  initialDrillPath?: string[];
  readOnly?: boolean;
  maxSelectable?: number;
  className?: string;
  style?: React.CSSProperties;
}

// ─── GEOMETRY HELPERS ─────────────────────────────────────────────

function polygonToPath(points: Array<{ x: number; y: number }>, edgeCurves?: any): string {
  if (!points || !points.length) return '';
  let d = \`M \${points[0].x} \${points[0].y}\`;
  for (let i = 0; i < points.length; i++) {
    const next = points[(i + 1) % points.length];
    const curve = edgeCurves ? edgeCurves[i] : null;
    if (curve) {
      d += \` C \${curve.cp1.x} \${curve.cp1.y} \${curve.cp2.x} \${curve.cp2.y} \${next.x} \${next.y}\`;
    } else {
      d += \` L \${next.x} \${next.y}\`;
    }
  }
  return d + ' Z';
}

function arcPath(
  cx: number,
  cy: number,
  innerR: number,
  outerR: number,
  sa: number,
  ea: number
): string {
  const largeArc = Math.abs(ea - sa) > Math.PI ? 1 : 0;
  const sweep = ea > sa ? 1 : 0;
  const x1 = cx + Math.cos(sa) * outerR;
  const y1 = cy + Math.sin(sa) * outerR;
  const x2 = cx + Math.cos(ea) * outerR;
  const y2 = cy + Math.sin(ea) * outerR;
  const x3 = cx + Math.cos(ea) * innerR;
  const y3 = cy + Math.sin(ea) * innerR;
  const x4 = cx + Math.cos(sa) * innerR;
  const y4 = cy + Math.sin(sa) * innerR;
  return [
    \`M \${x1} \${y1}\`,
    \`A \${outerR} \${outerR} 0 \${largeArc} \${sweep} \${x2} \${y2}\`,
    \`L \${x3} \${y3}\`,
    \`A \${innerR} \${innerR} 0 \${largeArc} \${1 - sweep} \${x4} \${y4}\`,
    'Z',
  ].join(' ');
}

function patternDefs(pattern: any, sectionId: string): { id: string; markup: string } | null {
  if (!pattern || pattern.type === 'none') return null;
  const id = \`pat-\${sectionId}\`;
  const color = pattern.color || '#ffffff';
  const size = Math.max(2, pattern.size || 4);
  const spacing = Math.max(size, pattern.spacing || 16);
  const opacity = pattern.opacity != null ? pattern.opacity : 0.35;
  let body = '';
  if (pattern.type === 'dots') {
    body = \`<circle cx="\${spacing / 2}" cy="\${spacing / 2}" r="\${size / 2}" fill="\${color}" fill-opacity="\${opacity}" />\`;
  } else if (pattern.type === 'grid') {
    body = \`<path d="M \${spacing} 0 L 0 0 0 \${spacing}" fill="none" stroke="\${color}" stroke-opacity="\${opacity}" stroke-width="\${Math.max(0.5, size / 4)}" />\`;
  } else if (pattern.type === 'stripes') {
    body = \`<rect width="\${Math.max(2, size)}" height="\${spacing}" fill="\${color}" fill-opacity="\${opacity}" />\`;
  } else if (pattern.type === 'custom') {
    body = pattern.customSvg || '';
  }
  const markup = \`<pattern id="\${id}" x="0" y="0" width="\${spacing}" height="\${spacing}" patternUnits="userSpaceOnUse">\${body}</pattern>\`;
  return { id, markup };
}

// ─── ICONS (inline) ───────────────────────────────────────────────

function ChairIcon({ color, size }: { color: string; size: number }) {
  return (
    <svg width={size} height={size} viewBox="0 0 24 24" fill="none">
      <rect x="4" y="2" width="16" height="5" rx="2" fill={color} />
      <rect x="5" y="9" width="14" height="9" rx="2" fill={color} />
      <rect x="2" y="8" width="4" height="10" rx="1.5" fill={color} opacity="0.85" />
      <rect x="18" y="8" width="4" height="10" rx="1.5" fill={color} opacity="0.85" />
      <rect x="6" y="18" width="3" height="4" rx="1" fill={color} opacity="0.7" />
      <rect x="15" y="18" width="3" height="4" rx="1" fill={color} opacity="0.7" />
    </svg>
  );
}

function ChairSimpleIcon({ color, size }: { color: string; size: number }) {
  return (
    <svg width={size} height={size} viewBox="0 0 24 24" fill="none">
      <rect x="4" y="3" width="16" height="14" rx="3" fill={color} />
      <rect x="4" y="17" width="4" height="4" rx="1" fill={color} opacity="0.7" />
      <rect x="16" y="17" width="4" height="4" rx="1" fill={color} opacity="0.7" />
    </svg>
  );
}

function WheelchairBadge({ color, size }: { color: string; size: number }) {
  return (
    <svg width={size} height={size} viewBox="0 0 24 24" fill="none">
      <circle cx="10" cy="4" r="2" fill={color} />
      <path
        d="M9 7v5h5l3 4m-5-4-2 5m-4-9a6 6 0 1 0 5 10"
        stroke={color}
        strokeWidth="2"
        strokeLinecap="round"
        strokeLinejoin="round"
        fill="none"
      />
    </svg>
  );
}

function SeatIcon({
  icon,
  color,
  size,
  customSvg,
}: {
  icon: string;
  color: string;
  size: number;
  customSvg?: string;
}) {
  if (icon === 'chair') return <ChairIcon color={color} size={size} />;
  if (icon === 'chair-simple') return <ChairSimpleIcon color={color} size={size} />;
  if (icon === 'custom' && customSvg) {
    return (
      <div
        style={{ width: size, height: size, color, display: 'block' }}
        // customSvg is sanitised at design-time by the tool that exported this file.
        dangerouslySetInnerHTML={{ __html: customSvg }}
      />
    );
  }
  const base: React.CSSProperties = {
    width: size,
    height: size,
    background: color,
    display: 'block',
  };
  if (icon === 'circle') return <div style={{ ...base, borderRadius: '50%' }} />;
  if (icon === 'rounded')
    return <div style={{ ...base, borderRadius: SEAT_CONFIG.layout.seatBorderRadius }} />;
  return <div style={base} />;
}

// ─── TREE HELPERS ─────────────────────────────────────────────────

function buildTreeIndex(sections: AnySection[]) {
  const index: Record<string, { section: AnySection; parents: string[] }> = {};
  const walk = (list: AnySection[], parents: string[]) => {
    for (const s of list) {
      index[s.id] = { section: s, parents };
      if (s.children && s.children.length) walk(s.children, [...parents, s.id]);
    }
  };
  walk(sections, []);
  return index;
}

function getVisibleSections(sections: AnySection[], drillStack: string[]): AnySection[] {
  if (!drillStack.length) return sections;
  let pool: AnySection[] = sections;
  for (const id of drillStack) {
    const found = pool.find((s: AnySection) => s.id === id);
    if (!found || !found.children) return [];
    pool = found.children;
  }
  return pool;
}

// ─── COMPONENT ────────────────────────────────────────────────────

export default function ${componentName}(props: ${componentName}Props) {
  const {
    initialSeatStates,
    onSeatSelect,
    onSelectionChange,
    onDrillIn,
    onDrillOut,
    initialDrillPath,
    readOnly = false,
    maxSelectable = Infinity,
    className,
    style,
  } = props;

  const venue = VENUE_DATA.venue;
  const allSections: AnySection[] = VENUE_DATA.sections as any;
  const stage = 'stage' in VENUE_DATA ? (VENUE_DATA as any).stage : undefined;
  const treeIndex = useMemo(() => buildTreeIndex(allSections), []);

  const [seatStates, setSeatStates] = useState<Record<string, SeatState>>(
    () => ({ ...(initialSeatStates ?? {}) })
  );
  useEffect(() => {
    if (initialSeatStates) setSeatStates({ ...initialSeatStates });
  }, [initialSeatStates]);

  const [selected, setSelected] = useState<string[]>([]);
  const [hoveredSeat, setHoveredSeat] = useState<string | null>(null);
  const [drillStack, setDrillStack] = useState<string[]>(initialDrillPath ?? []);

  const visibleSections = useMemo(
    () => getVisibleSections(allSections, drillStack),
    [drillStack]
  );

  const [scale, setScale] = useState(1);
  const [tx, setTx] = useState(0);
  const [ty, setTy] = useState(0);
  const viewportRef = useRef<HTMLDivElement>(null);
  const panState = useRef<{ startX: number; startY: number; tx: number; ty: number } | null>(null);
  const drillAnim = useRef<number | null>(null);

  const [marquee, setMarquee] = useState<null | { x1: number; y1: number; x2: number; y2: number }>(null);
  const marqueeRef = useRef(false);

  const computeFit = useCallback(
    (bounds: { x: number; y: number; width: number; height: number }) => {
      const el = viewportRef.current;
      if (!el) return { scale: 1, tx: 0, ty: 0 };
      const rect = el.getBoundingClientRect();
      const sx = (rect.width - 40) / bounds.width;
      const sy = (rect.height - 40) / bounds.height;
      const s = Math.max(SEAT_CONFIG.interaction.minZoom, Math.min(sx, sy, SEAT_CONFIG.interaction.maxZoom));
      return {
        scale: s,
        tx: (rect.width - bounds.width * s) / 2 - bounds.x * s,
        ty: (rect.height - bounds.height * s) / 2 - bounds.y * s,
      };
    },
    []
  );

  const animateToBounds = useCallback(
    (bounds: { x: number; y: number; width: number; height: number }) => {
      if (drillAnim.current) cancelAnimationFrame(drillAnim.current);
      const target = computeFit(bounds);
      const start = { scale, tx, ty };
      const t0 = performance.now();
      const duration = SEAT_CONFIG.interaction.drillAnimationMs;
      const tick = (now: number) => {
        const u = Math.min(1, (now - t0) / duration);
        const e = 1 - Math.pow(1 - u, 3);
        setScale(start.scale + (target.scale - start.scale) * e);
        setTx(start.tx + (target.tx - start.tx) * e);
        setTy(start.ty + (target.ty - start.ty) * e);
        if (u < 1) drillAnim.current = requestAnimationFrame(tick);
        else drillAnim.current = null;
      };
      drillAnim.current = requestAnimationFrame(tick);
    },
    [computeFit, scale, tx, ty]
  );

  const fitToViewport = useCallback(() => {
    const bounds = drillStack.length
      ? (treeIndex[drillStack[drillStack.length - 1]]?.section.bounds ?? {
          x: 0,
          y: 0,
          width: venue.width,
          height: venue.height,
        })
      : { x: 0, y: 0, width: venue.width, height: venue.height };
    const fit = computeFit(bounds);
    setScale(fit.scale);
    setTx(fit.tx);
    setTy(fit.ty);
  }, [computeFit, drillStack, treeIndex, venue.width, venue.height]);

  useEffect(() => {
    fitToViewport();
    const onResize = () => fitToViewport();
    window.addEventListener('resize', onResize);
    return () => window.removeEventListener('resize', onResize);
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  const localToCanvas = (clientX: number, clientY: number) => {
    const rect = viewportRef.current?.getBoundingClientRect();
    if (!rect) return { x: 0, y: 0 };
    return {
      x: (clientX - rect.left - tx) / scale,
      y: (clientY - rect.top - ty) / scale,
    };
  };

  const visibleSeats = useMemo(() => {
    const list: Array<{ seat: any; section: AnySection }> = [];
    for (const section of visibleSections) {
      if (section.children && section.children.length) continue;
      for (const seat of section.seats || []) list.push({ seat, section });
    }
    return list;
  }, [visibleSections]);

  const resolveSeatInfo = useCallback(
    (seatId: string): SeatInfo | null => {
      for (const id of Object.keys(treeIndex)) {
        const entry = treeIndex[id];
        const section = entry.section;
        if (!section.seats) continue;
        const seat = section.seats.find((s: any) => s.id === seatId);
        if (seat) {
          const state = (seatStates[seat.id] ?? seat.state) as SeatState;
          return {
            id: seat.id,
            label: seat.customLabel || seat.label,
            rowLabel: seat.rowLabel,
            seatNumber: seat.seatNumber,
            sectionId: section.id,
            sectionName: section.name,
            sectionPath: [...entry.parents, section.id],
            price: section.price,
            currency: section.currency,
            state,
            accessible: seat.accessible,
          };
        }
      }
      return null;
    },
    [treeIndex, seatStates]
  );

  const updateSelection = useCallback(
    (next: string[]) => {
      setSelected(next);
      onSelectionChange?.(next);
    },
    [onSelectionChange]
  );

  const drillInto = useCallback(
    (sectionId: string) => {
      const entry = treeIndex[sectionId];
      if (!entry || !entry.section.children || !entry.section.children.length) return;
      const nextStack = [...entry.parents, sectionId];
      setDrillStack(nextStack);
      animateToBounds(entry.section.bounds);
      updateSelection([]);
      onDrillIn?.(sectionId);
    },
    [treeIndex, animateToBounds, updateSelection, onDrillIn]
  );

  const drillUp = useCallback(() => {
    if (!drillStack.length) return;
    const next = drillStack.slice(0, -1);
    setDrillStack(next);
    updateSelection([]);
    if (next.length) {
      const parent = treeIndex[next[next.length - 1]]?.section;
      if (parent) animateToBounds(parent.bounds);
    } else {
      animateToBounds({ x: 0, y: 0, width: venue.width, height: venue.height });
    }
    onDrillOut?.();
  }, [drillStack, treeIndex, animateToBounds, updateSelection, onDrillOut, venue.width, venue.height]);

  const drillToRoot = useCallback(() => {
    setDrillStack([]);
    updateSelection([]);
    animateToBounds({ x: 0, y: 0, width: venue.width, height: venue.height });
  }, [animateToBounds, updateSelection, venue.width, venue.height]);

  const handleSectionClick = useCallback(
    (section: AnySection, e: React.MouseEvent) => {
      const container = section.children && section.children.length;
      const interactions = section.interactions || {};
      const action = interactions.clickAction
        || (container ? SEAT_CONFIG.interaction.defaultContainerClick : 'select');

      if (action === 'drillIn' && container) {
        e.stopPropagation();
        drillInto(section.id);
      } else if (action === 'url' && interactions.url) {
        e.stopPropagation();
        window.open(interactions.url, '_blank', 'noopener,noreferrer');
      } else if (action === 'event' && interactions.eventName) {
        e.stopPropagation();
        viewportRef.current?.dispatchEvent(
          new CustomEvent(interactions.eventName, {
            detail: { sectionId: section.id, sectionName: section.name },
            bubbles: true,
          })
        );
      }
    },
    [drillInto]
  );

  const toggleSeat = useCallback(
    (seatId: string, opts: { additive: boolean }) => {
      if (readOnly) return;
      const info = resolveSeatInfo(seatId);
      if (!info) return;
      if (info.state === 'reserved' || info.state === 'disabled') return;

      setSelected((prev) => {
        let next: string[];
        if (prev.includes(seatId)) {
          next = prev.filter((id) => id !== seatId);
        } else if (opts.additive) {
          next = [...prev, seatId];
        } else {
          next = [seatId];
        }
        if (next.length > maxSelectable) next = next.slice(-maxSelectable);
        onSelectionChange?.(next);
        onSeatSelect?.(seatId, { ...info, state: 'available' });
        return next;
      });
    },
    [readOnly, resolveSeatInfo, maxSelectable, onSelectionChange, onSeatSelect]
  );

  // ─── Wheel zoom ──
  useEffect(() => {
    const el = viewportRef.current;
    if (!el) return;
    const onWheel = (e: WheelEvent) => {
      e.preventDefault();
      const factor = Math.exp(-e.deltaY * SEAT_CONFIG.interaction.wheelZoomSpeed);
      const rect = el.getBoundingClientRect();
      const mx = e.clientX - rect.left;
      const my = e.clientY - rect.top;
      setScale((prev) => {
        const next = Math.max(
          SEAT_CONFIG.interaction.minZoom,
          Math.min(SEAT_CONFIG.interaction.maxZoom, prev * factor)
        );
        const ratio = next / prev;
        setTx((prevTx) => mx - (mx - prevTx) * ratio);
        setTy((prevTy) => my - (my - prevTy) * ratio);
        return next;
      });
    };
    el.addEventListener('wheel', onWheel, { passive: false });
    return () => el.removeEventListener('wheel', onWheel);
  }, []);

  // ─── Pan & marquee ──
  const handleMouseDown = (e: React.MouseEvent) => {
    const isPanButton = e.button === 1 || e.button === 2;
    const isLeftOnEmpty = e.button === 0 && e.target === e.currentTarget;

    if (isPanButton) {
      e.preventDefault();
      panState.current = { startX: e.clientX, startY: e.clientY, tx, ty };
      return;
    }

    if (isLeftOnEmpty && SEAT_CONFIG.interaction.marqueeSelect && !readOnly) {
      const { x, y } = localToCanvas(e.clientX, e.clientY);
      if (!e.shiftKey) updateSelection([]);
      marqueeRef.current = true;
      setMarquee({ x1: x, y1: y, x2: x, y2: y });
    } else if (isLeftOnEmpty && !e.shiftKey) {
      updateSelection([]);
    }
  };

  useEffect(() => {
    const onMove = (e: MouseEvent) => {
      if (panState.current) {
        setTx(panState.current.tx + (e.clientX - panState.current.startX));
        setTy(panState.current.ty + (e.clientY - panState.current.startY));
      } else if (marqueeRef.current) {
        const { x, y } = localToCanvas(e.clientX, e.clientY);
        setMarquee((m) => (m ? { ...m, x2: x, y2: y } : m));
      }
    };
    const onUp = () => {
      panState.current = null;
      if (marqueeRef.current) {
        marqueeRef.current = false;
        setMarquee((m) => {
          if (!m) return m;
          const minX = Math.min(m.x1, m.x2);
          const maxX = Math.max(m.x1, m.x2);
          const minY = Math.min(m.y1, m.y2);
          const maxY = Math.max(m.y1, m.y2);
          if (maxX - minX > 3 && maxY - minY > 3) {
            const inBox: string[] = [];
            for (const { seat, section } of visibleSeats) {
              const sx = section.bounds.x + seat.bounds.x + seat.bounds.width / 2;
              const sy = section.bounds.y + seat.bounds.y + seat.bounds.height / 2;
              const state = (seatStates[seat.id] ?? seat.state) as SeatState;
              if (state !== 'available') continue;
              if (sx >= minX && sx <= maxX && sy >= minY && sy <= maxY) inBox.push(seat.id);
            }
            setSelected((prev) => {
              const combined = Array.from(new Set([...prev, ...inBox]));
              const capped = combined.length > maxSelectable
                ? combined.slice(0, maxSelectable)
                : combined;
              onSelectionChange?.(capped);
              return capped;
            });
          }
          return null;
        });
      }
    };
    window.addEventListener('mousemove', onMove);
    window.addEventListener('mouseup', onUp);
    return () => {
      window.removeEventListener('mousemove', onMove);
      window.removeEventListener('mouseup', onUp);
    };
  }, [visibleSeats, seatStates, maxSelectable, onSelectionChange, tx, ty, scale]);

  const handleContextMenu = (e: React.MouseEvent) => e.preventDefault();

  // ─── Keyboard ──
  const handleKeyDown = useCallback(
    (e: React.KeyboardEvent) => {
      if (e.key === 'Escape') {
        if (selected.length) {
          updateSelection([]);
          return;
        }
        if (SEAT_CONFIG.interaction.allowEscapeToDrillUp && drillStack.length) {
          drillUp();
        }
        return;
      }
      if (!['ArrowLeft', 'ArrowRight', 'ArrowUp', 'ArrowDown'].includes(e.key)) return;
      const active = document.activeElement as HTMLElement | null;
      if (!active || !active.dataset.seatId) return;
      e.preventDefault();

      const seats = Array.from(
        viewportRef.current?.querySelectorAll<HTMLElement>('[data-seat-id][data-interactable="1"]') ?? []
      );
      const currentRect = active.getBoundingClientRect();
      const cx = currentRect.left + currentRect.width / 2;
      const cy = currentRect.top + currentRect.height / 2;

      let best: { el: HTMLElement; score: number } | null = null;
      for (const el of seats) {
        if (el === active) continue;
        const r = el.getBoundingClientRect();
        const dx = r.left + r.width / 2 - cx;
        const dy = r.top + r.height / 2 - cy;
        let aligned = false;
        if (e.key === 'ArrowRight') aligned = dx > 0 && Math.abs(dy) <= Math.abs(dx);
        if (e.key === 'ArrowLeft')  aligned = dx < 0 && Math.abs(dy) <= Math.abs(dx);
        if (e.key === 'ArrowDown')  aligned = dy > 0 && Math.abs(dx) <= Math.abs(dy);
        if (e.key === 'ArrowUp')    aligned = dy < 0 && Math.abs(dx) <= Math.abs(dy);
        if (!aligned) continue;
        const score = dx * dx + dy * dy;
        if (!best || score < best.score) best = { el, score };
      }
      if (best) best.el.focus();
    },
    [updateSelection, drillStack, drillUp, selected.length]
  );

  // ─── Render ──
  const marqueeStyle: React.CSSProperties | null = marquee
    ? {
        position: 'absolute',
        left: Math.min(marquee.x1, marquee.x2),
        top: Math.min(marquee.y1, marquee.y2),
        width: Math.abs(marquee.x2 - marquee.x1),
        height: Math.abs(marquee.y2 - marquee.y1),
        border: \`1.5px dashed \${SEAT_CONFIG.colors.marqueeStroke}\`,
        background: SEAT_CONFIG.colors.marqueeFill,
        pointerEvents: 'none',
      }
    : null;

  const breadcrumbSections = drillStack
    .map((id) => treeIndex[id]?.section)
    .filter(Boolean);

  return (
    <div
      ref={viewportRef}
      className={className}
      style={{
        position: 'relative',
        width: '100%',
        height: '100%',
        minHeight: 400,
        overflow: 'hidden',
        background: SEAT_CONFIG.colors.background,
        borderRadius: 8,
        cursor: panState.current ? 'grabbing' : 'default',
        userSelect: 'none',
        ...style,
      }}
      onMouseDown={handleMouseDown}
      onContextMenu={handleContextMenu}
      onKeyDown={handleKeyDown}
      tabIndex={0}
      role="application"
      aria-label={\`Seat map for \${venue.name}\`}
    >
      <div
        style={{
          position: 'absolute',
          left: 0,
          top: 0,
          width: venue.width,
          height: venue.height,
          transform: \`translate(\${tx}px, \${ty}px) scale(\${scale})\`,
          transformOrigin: '0 0',
        }}
      >
        {stage && !drillStack.length && (
          <div
            style={{
              position: 'absolute',
              left: stage.bounds.x,
              top: stage.bounds.y,
              width: stage.bounds.width,
              height: stage.bounds.height,
              background: stage.fill,
              color: 'rgba(255,255,255,0.85)',
              borderRadius: 8,
              display: 'flex',
              alignItems: 'center',
              justifyContent: 'center',
              fontWeight: 700,
              letterSpacing: 4,
              fontSize: 14,
            }}
          >
            {stage.label || 'STAGE'}
          </div>
        )}

        {[...visibleSections]
          .sort((a: AnySection, b: AnySection) => a.zIndex - b.zIndex)
          .map((section: AnySection) => (
            <SectionRender
              key={section.id}
              section={section}
              selected={selected}
              hoveredSeat={hoveredSeat}
              seatStates={seatStates}
              onSeatHover={setHoveredSeat}
              onSeatClick={(seatId, additive) =>
                toggleSeat(seatId, { additive: additive && SEAT_CONFIG.interaction.shiftMultiSelect })
              }
              onSectionClick={handleSectionClick}
            />
          ))}

        {marqueeStyle && <div style={marqueeStyle} />}
      </div>

      {SEAT_CONFIG.interaction.showBreadcrumb && drillStack.length > 0 && (
        <Breadcrumb
          venueName={venue.name}
          sections={breadcrumbSections}
          onRoot={drillToRoot}
          onUp={drillUp}
        />
      )}

      <Controls
        onZoomIn={() =>
          setScale((s) => Math.min(SEAT_CONFIG.interaction.maxZoom, s + SEAT_CONFIG.interaction.zoomStep))
        }
        onZoomOut={() =>
          setScale((s) => Math.max(SEAT_CONFIG.interaction.minZoom, s - SEAT_CONFIG.interaction.zoomStep))
        }
        onFit={fitToViewport}
        zoom={scale}
      />

      <Legend selectedCount={selected.length} maxSelectable={maxSelectable} />
    </div>
  );
}

// ─── SECTION RENDER ──────────────────────────────────────────────

function SectionRender({
  section,
  selected,
  hoveredSeat,
  seatStates,
  onSeatHover,
  onSeatClick,
  onSectionClick,
}: {
  section: AnySection;
  selected: string[];
  hoveredSeat: string | null;
  seatStates: Record<string, SeatState>;
  onSeatHover: (id: string | null) => void;
  onSeatClick: (id: string, additive: boolean) => void;
  onSectionClick: (section: AnySection, e: React.MouseEvent) => void;
}) {
  const icon = section.seatIcon || SEAT_CONFIG.layout.seatIcon;
  const isPolygon = section.type === 'polygon' && section.points && section.points.length >= 3;
  const isArc = section.type === 'arc' && section.arc;
  const isContainer = section.children && section.children.length > 0;
  const hasSeats = !isContainer && section.seats && section.seats.length > 0;
  const pattern = patternDefs(section.pattern, section.id);
  const interactions = section.interactions || {};
  const [hovered, setHovered] = React.useState(false);
  const hoverScale = interactions.hoverScale && interactions.hoverScale !== 1 ? interactions.hoverScale : 1;
  const appliedScale = hovered ? hoverScale : 1;
  const title = interactions.tooltip
    || (isContainer ? \`\${section.name} — \${section.children.length} sub-sections\` : section.name);

  const cornerRadius =
    section.cornerRadius != null ? section.cornerRadius : SEAT_CONFIG.layout.sectionBorderRadius;

  return (
    <div
      title={title}
      onMouseEnter={() => setHovered(true)}
      onMouseLeave={() => setHovered(false)}
      onClick={(e) => onSectionClick(section, e)}
      style={{
        position: 'absolute',
        left: section.bounds.x,
        top: section.bounds.y,
        width: section.bounds.width,
        height: section.bounds.height,
        transform: [
          section.rotation ? \`rotate(\${section.rotation}deg)\` : '',
          appliedScale !== 1 ? \`scale(\${appliedScale})\` : '',
        ].filter(Boolean).join(' ') || undefined,
        transformOrigin: 'center center',
        opacity: section.opacity,
        zIndex: section.zIndex,
        cursor: isContainer || interactions.clickAction === 'url' || interactions.clickAction === 'event'
          ? 'pointer'
          : 'default',
        transition: hoverScale !== 1 ? 'transform 0.15s ease' : undefined,
      }}
    >
      {isPolygon ? (
        <svg
          width={section.bounds.width}
          height={section.bounds.height}
          viewBox={\`0 0 \${section.bounds.width} \${section.bounds.height}\`}
          preserveAspectRatio="none"
          style={{ position: 'absolute', inset: 0 }}
        >
          {pattern && <defs dangerouslySetInnerHTML={{ __html: pattern.markup }} />}
          <path
            d={polygonToPath(section.points, section.edgeCurves)}
            fill={section.fill}
            stroke={section.stroke}
            strokeWidth={section.strokeWidth}
          />
          {pattern && (
            <path d={polygonToPath(section.points, section.edgeCurves)} fill={\`url(#\${pattern.id})\`} />
          )}
        </svg>
      ) : isArc ? (
        <svg
          width={section.bounds.width}
          height={section.bounds.height}
          viewBox={\`0 0 \${section.bounds.width} \${section.bounds.height}\`}
          preserveAspectRatio="none"
          style={{ position: 'absolute', inset: 0 }}
        >
          {pattern && <defs dangerouslySetInnerHTML={{ __html: pattern.markup }} />}
          <path
            d={arcPath(
              section.bounds.width / 2,
              section.bounds.height / 2,
              section.arc.innerRadius,
              section.arc.outerRadius,
              section.arc.startAngle,
              section.arc.endAngle
            )}
            fill={section.fill}
            stroke={section.stroke}
            strokeWidth={section.strokeWidth}
          />
          {pattern && (
            <path
              d={arcPath(
                section.bounds.width / 2,
                section.bounds.height / 2,
                section.arc.innerRadius,
                section.arc.outerRadius,
                section.arc.startAngle,
                section.arc.endAngle
              )}
              fill={\`url(#\${pattern.id})\`}
            />
          )}
        </svg>
      ) : (
        <div
          style={{
            position: 'absolute',
            inset: 0,
            background: section.fill,
            border: \`\${section.strokeWidth}px solid \${section.stroke}\`,
            borderRadius:
              section.type === 'circle' || section.type === 'ellipse'
                ? '50%'
                : cornerRadius,
            overflow: 'hidden',
          }}
        >
          {pattern && (
            <svg
              style={{ position: 'absolute', inset: 0, width: '100%', height: '100%' }}
              preserveAspectRatio="none"
            >
              <defs dangerouslySetInnerHTML={{ __html: pattern.markup }} />
              <rect width="100%" height="100%" fill={\`url(#\${pattern.id})\`} />
            </svg>
          )}
        </div>
      )}

      {isContainer && (
        <div
          style={{
            position: 'absolute',
            top: 6,
            right: 6,
            padding: '2px 6px',
            borderRadius: 999,
            background: SEAT_CONFIG.colors.breadcrumbActive,
            color: '#fff',
            fontSize: 10,
            fontWeight: 700,
            letterSpacing: 0.5,
            pointerEvents: 'none',
          }}
        >
          {section.children.length}
        </div>
      )}

      {SEAT_CONFIG.layout.showSectionLabels && section.labelVisible && (
        <div
          style={{
            position: 'absolute',
            left: 0,
            right: 0,
            top: hasSeats ? -18 : '50%',
            transform: hasSeats ? undefined : 'translateY(-50%)',
            textAlign: 'center',
            color: SEAT_CONFIG.colors.sectionLabel,
            textShadow: '0 1px 3px rgba(0,0,0,0.85)',
            fontSize: Math.max(10, Math.min(16, section.bounds.width / 15)),
            fontWeight: 600,
            letterSpacing: 0.3,
            pointerEvents: 'none',
          }}
        >
          {section.name}
          {SEAT_CONFIG.layout.showPriceBadges && section.price > 0 && (
            <span style={{ marginLeft: 8, opacity: 0.75, fontWeight: 400 }}>
              {section.currency}
              {section.price}
            </span>
          )}
        </div>
      )}

      {hasSeats && section.seats.map((seat: any) => {
        const state = (seatStates[seat.id] ?? seat.state) as SeatState;
        const isSelected = selected.includes(seat.id);
        const isHovered = hoveredSeat === seat.id;
        const color = isSelected
          ? SEAT_CONFIG.colors.selected
          : state === 'reserved'
            ? SEAT_CONFIG.colors.reserved
            : state === 'disabled'
              ? SEAT_CONFIG.colors.disabled
              : SEAT_CONFIG.colors.available;
        const size = Math.min(seat.bounds.width, seat.bounds.height);
        const isInteractable = state === 'available';

        return (
          <div
            key={seat.id}
            role="button"
            aria-label={\`\${section.name} \${seat.label} \${state}\${seat.accessible ? ' accessible' : ''}\`}
            aria-pressed={isSelected}
            aria-disabled={!isInteractable}
            data-seat-id={seat.id}
            data-interactable={isInteractable ? '1' : '0'}
            tabIndex={isInteractable ? 0 : -1}
            onClick={(e) => {
              e.stopPropagation();
              if (!isInteractable) return;
              onSeatClick(seat.id, e.shiftKey);
            }}
            onKeyDown={(e) => {
              if ((e.key === 'Enter' || e.key === ' ') && isInteractable) {
                e.preventDefault();
                onSeatClick(seat.id, e.shiftKey);
              }
            }}
            onMouseEnter={() => onSeatHover(seat.id)}
            onMouseLeave={() => onSeatHover(null)}
            title={\`\${seat.label} — \${section.name}\${seat.accessible ? ' — accessible' : ''} — \${section.currency}\${section.price}\`}
            style={{
              position: 'absolute',
              left: seat.bounds.x,
              top: seat.bounds.y,
              width: seat.bounds.width,
              height: seat.bounds.height,
              cursor: isInteractable ? 'pointer' : 'not-allowed',
              display: 'flex',
              alignItems: 'center',
              justifyContent: 'center',
              opacity: state === 'disabled' ? 0.45 : 1,
              transform: isHovered && isInteractable ? 'scale(1.15)' : 'scale(1)',
              transition: 'transform 0.12s ease',
              outline: isSelected
                ? \`2px solid \${SEAT_CONFIG.colors.selected}\`
                : isHovered && SEAT_CONFIG.interaction.hoverOutline && isInteractable
                  ? \`2px solid \${SEAT_CONFIG.colors.available}\`
                  : 'none',
              outlineOffset: 2,
              borderRadius: icon === 'circle' ? '50%' : SEAT_CONFIG.layout.seatBorderRadius,
            }}
          >
            <SeatIcon icon={icon} color={color} size={size} customSvg={section.customSeatIcon?.svg} />
            {seat.accessible && (
              <div
                style={{
                  position: 'absolute',
                  top: -4,
                  right: -4,
                  background: SEAT_CONFIG.colors.accessibility,
                  borderRadius: '50%',
                  width: Math.max(10, size * 0.35),
                  height: Math.max(10, size * 0.35),
                  display: 'flex',
                  alignItems: 'center',
                  justifyContent: 'center',
                }}
              >
                <WheelchairBadge color="#fff" size={Math.max(8, size * 0.28)} />
              </div>
            )}
          </div>
        );
      })}
    </div>
  );
}

// ─── BREADCRUMB ──────────────────────────────────────────────────

function Breadcrumb({
  venueName,
  sections,
  onRoot,
  onUp,
}: {
  venueName: string;
  sections: AnySection[];
  onRoot: () => void;
  onUp: () => void;
}) {
  return (
    <div
      style={{
        position: 'absolute',
        top: 12,
        left: '50%',
        transform: 'translateX(-50%)',
        display: 'flex',
        alignItems: 'center',
        gap: 6,
        padding: '6px 10px',
        borderRadius: 999,
        background: SEAT_CONFIG.colors.breadcrumbBg,
        border: '1px solid rgba(255,255,255,0.1)',
        color: '#fff',
        fontSize: 12,
        backdropFilter: 'blur(8px)',
        zIndex: 10,
      }}
    >
      <button
        onClick={onRoot}
        style={{
          background: 'transparent',
          border: 0,
          color: '#fff',
          fontSize: 12,
          fontWeight: 500,
          cursor: 'pointer',
          padding: '2px 8px',
          borderRadius: 999,
        }}
      >
        {venueName}
      </button>
      {sections.map((s, i) => (
        <React.Fragment key={s.id}>
          <span style={{ opacity: 0.5 }}>›</span>
          <span
            style={{
              padding: '2px 8px',
              borderRadius: 999,
              background: i === sections.length - 1 ? SEAT_CONFIG.colors.breadcrumbActive : 'transparent',
              fontWeight: i === sections.length - 1 ? 600 : 400,
            }}
          >
            {s.name}
          </span>
        </React.Fragment>
      ))}
      <button
        onClick={onUp}
        style={{
          marginLeft: 4,
          background: 'rgba(255,255,255,0.08)',
          border: 0,
          color: '#fff',
          fontSize: 11,
          cursor: 'pointer',
          padding: '2px 8px',
          borderRadius: 999,
        }}
      >
        ← Back
      </button>
    </div>
  );
}

function Controls({
  onZoomIn,
  onZoomOut,
  onFit,
  zoom,
}: {
  onZoomIn: () => void;
  onZoomOut: () => void;
  onFit: () => void;
  zoom: number;
}) {
  return (
    <div
      style={{
        position: 'absolute',
        top: 12,
        right: 12,
        display: 'flex',
        gap: 4,
        background: 'rgba(15,23,42,0.85)',
        border: '1px solid rgba(255,255,255,0.1)',
        borderRadius: 8,
        padding: 4,
        backdropFilter: 'blur(8px)',
      }}
    >
      <button type="button" onClick={onZoomOut} style={ctrlBtnStyle} aria-label="Zoom out">−</button>
      <div
        style={{
          color: 'rgba(255,255,255,0.8)',
          fontSize: 11,
          display: 'flex',
          alignItems: 'center',
          padding: '0 8px',
          minWidth: 48,
          justifyContent: 'center',
          fontFamily: 'ui-monospace, monospace',
        }}
      >
        {Math.round(zoom * 100)}%
      </div>
      <button type="button" onClick={onZoomIn} style={ctrlBtnStyle} aria-label="Zoom in">+</button>
      <button type="button" onClick={onFit} style={ctrlBtnStyle} aria-label="Fit to view">⊡</button>
    </div>
  );
}

const ctrlBtnStyle: React.CSSProperties = {
  width: 28,
  height: 28,
  display: 'inline-flex',
  alignItems: 'center',
  justifyContent: 'center',
  border: 0,
  background: 'transparent',
  color: 'rgba(255,255,255,0.9)',
  cursor: 'pointer',
  borderRadius: 4,
  fontSize: 14,
};

function Legend({
  selectedCount,
  maxSelectable,
}: {
  selectedCount: number;
  maxSelectable: number;
}) {
  const items = [
    { color: SEAT_CONFIG.colors.available, label: 'Available' },
    { color: SEAT_CONFIG.colors.selected, label: 'Selected' },
    { color: SEAT_CONFIG.colors.reserved, label: 'Reserved' },
    { color: SEAT_CONFIG.colors.disabled, label: 'Unavailable' },
  ];
  return (
    <div
      style={{
        position: 'absolute',
        bottom: 12,
        left: 12,
        display: 'flex',
        gap: 12,
        alignItems: 'center',
        background: 'rgba(15,23,42,0.85)',
        border: '1px solid rgba(255,255,255,0.1)',
        borderRadius: 8,
        padding: '6px 10px',
        color: 'rgba(255,255,255,0.85)',
        fontSize: 11,
      }}
    >
      {items.map((item) => (
        <span key={item.label} style={{ display: 'flex', gap: 6, alignItems: 'center' }}>
          <span
            style={{
              width: 10,
              height: 10,
              borderRadius: '50%',
              background: item.color,
            }}
          />
          {item.label}
        </span>
      ))}
      <span style={{ marginLeft: 8, opacity: 0.7 }}>
        {selectedCount}
        {Number.isFinite(maxSelectable) ? \` / \${maxSelectable}\` : ''} selected
      </span>
    </div>
  );
}
`;
}
