import type { VenueData } from '@/types';
import runtimeSource from '@/export/SeatMapRuntime.tsx?raw';

/**
 * Transforms the raw SeatMapRuntime.tsx source into a self-contained snippet
 * that can be embedded inside a user's exported file. The snippet:
 *   - has no `import React` line (it will be re-declared at the top of the
 *     exported file)
 *   - has no `export` keywords (so SEAT_CONFIG / helpers / SeatMapRuntime
 *     become file-local)
 *   - keeps SeatState / SeatInfo as private declarations that we re-export
 *     explicitly from the exported file
 */
function inlineRuntime(): string {
  let src = runtimeSource;
  // Drop the leading jsdoc header comment.
  src = src.replace(/^\/\*\*[\s\S]*?\*\/\s*/, '');
  // Drop the `import React, { ... } from 'react';` block.
  src = src.replace(/import React[\s\S]*?from\s*['"]react['"];\s*/m, '');
  // Strip `export default` and bare `export` keywords on top-level
  // declarations. Our runtime only uses these at the start of a line.
  src = src.replace(/^export default /gm, '');
  src = src.replace(/^export /gm, '');
  return src.trim();
}

/**
 * Builds a self-contained React TSX file that renders the given venue as an
 * interactive seat map with nested sections, pattern fills, arc sections and
 * runtime interactions. The output has zero dependencies beyond React, uses
 * inline SVG for every visual element and exposes props for state + callbacks.
 *
 * The runtime body is shared with the in-app /benchmark page via a `?raw`
 * import of src/export/SeatMapRuntime.tsx — so any optimization applied to
 * the runtime automatically ships in users' exported files.
 */
export function generateComponentSource(data: VenueData, componentName = 'SeatMap'): string {
  const venueJson = JSON.stringify(data, null, 2);
  const runtime = inlineRuntime();

  return `/**
 * ${componentName} — generated by Eskat Seating Design Tool
 *
 * Self-contained interactive seat map. Zero dependencies beyond React.
 *
 * Features:
 *   - Nested sections (container → sub-sections → seats) with animated drill-in
 *   - Pattern fills (dots, grid, stripes, custom SVG)
 *   - Arc sections, polygons with bezier-curved edges
 *   - Runtime interactions: tooltip, select / drillIn / url / event
 *   - Marquee + shift multi-select, zoom/pan, arrow-key navigation
 *   - Viewport culling for smooth rendering of 30k+ seats
 *
 * Props:
 *   - initialSeatStates?: Record<string, 'available' | 'reserved' | 'disabled'>
 *   - onSeatSelect?:      (seatId, seatInfo) => void
 *   - onSelectionChange?: (selectedIds) => void
 *   - onDrillIn?:         (sectionId) => void
 *   - onDrillOut?:        () => void
 *   - initialDrillPath?:  string[]
 *   - readOnly?:          boolean
 *   - maxSelectable?:     number
 *   - className?:         string
 *
 * To customise colors, zoom, or layout behavior, edit the SEAT_CONFIG
 * object below — it is the first declaration in this file for that reason.
 */

import React, {
  useCallback,
  useEffect,
  useLayoutEffect,
  useMemo,
  useRef,
  useState,
} from 'react';

${runtime}

// ─── INLINE VENUE DATA ────────────────────────────────────────────
// Generated from the Eskat designer. Do not edit by hand — regenerate
// instead to preserve layout fidelity.

const VENUE_DATA = ${venueJson} as const;

// ─── PUBLIC API ───────────────────────────────────────────────────

export type { SeatState, SeatInfo };

export interface ${componentName}Props {
  initialSeatStates?: Record<string, SeatState>;
  onSeatSelect?: (seatId: string, info: SeatInfo) => void;
  onSelectionChange?: (selectedIds: string[]) => void;
  onDrillIn?: (sectionId: string) => void;
  onDrillOut?: () => void;
  initialDrillPath?: string[];
  readOnly?: boolean;
  maxSelectable?: number;
  className?: string;
  style?: React.CSSProperties;
}

export default function ${componentName}(props: ${componentName}Props) {
  return <SeatMapRuntime {...props} venueData={VENUE_DATA as unknown as SeatMapRuntimeProps['venueData']} />;
}
`;
}
